#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

function run_cmd {
  exec $*
}

function main {
  case "$LOG_LEVEL" in
    '1')
      VERBOSITY='-v'
      ;;
    '2')
      VERBOSITY='-vv'
      ;;
    '3')
      VERBOSITY='-vvv'
      ;;
    *)
      VERBOSITY=
      ;;
  esac

  run_cmd "/usr/bin/memcached ${VERBOSITY} -u nobody -m ${CACHE_SIZE} -p ${PORT} -l 0.0.0.0 ${EXTRA_OPTS}"
}

: ${EXTRA_OPTS:=}
: ${CACHE_SIZE:=64}
: ${PORT:=11211}
: ${LOG_LEVEL:=1}

ulimit -n 32768
main
exit 0